CREATE TABLE IF NOT EXISTS samples(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(256) NOT NULL
);